backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  publish_mode: editorial_workflow
  
# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /imag

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "src/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", default: "", required: true}
      - {label: "Slug", name: "slug", widget: "string", required: true}
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Publish Date", name: "published_at", widget: "datetime"}
      - {label: "Update Date", name: "updated_at", widget: "datetime"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Featured Image", name: "feature_image", widget: "image"}
      - {label: "Meta Description", name: "meta_description", widget: "string"}
      - {label: "Enable Comments", name: "comment", widget: "boolean"}
      - {label: "Author", name: "author", widget: "string", default: "akansh"}
      - {label: "Body", name: "body", widget: "markdown"}
